config/routes.rb
Rails.application.routes.draw do

  root "home#index"

  resources :items do
    member do
      get  :materials      # /items/:id/materials
      post :materials_post      # bulk add/update
    end
  end
  get  "shopping",          to: "shopping#index"
  post "shopping/purchase", to: "shopping#purchase", as: :shopping_purchase

  resources :material_requirements
  resources :inventory_items
  resources :item_blocks
  resources :categories
  resources :moods
  resources :locations
  resources :shops
  resources :items

  get  "/login",  to: "sessions#new"
  post "/login",  to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  get  "/planner", to: "schedule_entries#index", as: :planner
  resources :schedule_entries, only: [:create, :destroy] do
    collection do
      delete :clear # ?on_date=YYYY-MM-DD&day_part=morning
    end
  end

end

app/models/inventory_item.rb
# app/models/inventory_item.rb
class InventoryItem < ApplicationRecord
  belongs_to :location, optional: true
  validates :name, presence: true, uniqueness: true
  has_many :item_inventories, dependent: :destroy
  has_many :items, through: :item_inventories
  belongs_to :shop
  validates :shop, presence: true
end

app/controllers/inventory_items_controller.rb
# app/controllers/inventory_items_controller.rb
class InventoryItemsController < ApplicationController
  before_action :set_inventory_item, only: %i[show edit update destroy]

  def index
    @inventory_items = InventoryItem.includes(:location).order(:name)
    if !params[:zeros]
      @inventory_items = @inventory_items.where("qty_have > 0")
    end
  end

  def show; end

  def new
    @inventory_item = InventoryItem.new
  end

  def edit; end

  def create
    @inventory_item = InventoryItem.new(inventory_item_params)
    if @inventory_item.save
      redirect_to inventory_items_path, notice: "Inventory item created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @inventory_item.update(inventory_item_params)
      redirect_to inventory_items_path, notice: "Inventory item updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @inventory_item.destroy
    redirect_to inventory_items_url, notice: "Inventory item deleted."
  end

  private
  def set_inventory_item
    @inventory_item = InventoryItem.find(params[:id])
  end

  def inventory_item_params
    params.require(:inventory_item).permit(:name, :qty_have, :unit, :location_id, :shop_id)
  end
end

app/views/inventory_items/_form.html.erb
<!-- app/views/inventory_items/_form.html.erb -->
<%= form_with(model: inventory_item) do |f| %>
  <% if inventory_item.errors.any? %>
    <div style="color:red"><%= inventory_item.errors.full_messages.to_sentence %></div>
  <% end %>
  <p>Name<br><%= f.text_field :name, required: true %></p>
  <p>Qty have<br><%= f.number_field :qty_have, step: 0.01, min: 0 %></p>
  <p>Location<br>
    <%= f.collection_select :location_id, Location.order(:name), :id, :name, include_blank: true %>
  </p>
   <p>Default Vendor<br>
    <%= f.collection_select :shop_id, Shop.order(:name), :id, :name %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/inventory_items/edit.html.erb
<!-- app/views/inventory_items/edit.html.erb -->
<h1>Edit Inventory Item</h1>
<%= render "form", inventory_item: @inventory_item %>
<p><%= link_to "Back", inventory_items_path %></p>

app/views/inventory_items/index.html.erb
<!-- app/views/inventory_items/index.html.erb -->
<h1>Inventory</h1>

<p><%= link_to "Back", root_path %>
<%= link_to "New Inventory Item", new_inventory_item_path %>
<%= link_to "Zeros", inventory_items_path(zeros: 1) %></p>
<table border="1" cellpadding="6">
  <tr><th>Name</th><th>Qty</th><th>Location</th><th></th></tr>
  <% @inventory_items.each do |ii| %>
    <tr>
      <td><%= link_to ii.name, edit_inventory_item_path(ii) %></td>
      <td><%= ii.qty_have %></td>
      <td><%= ii.location&.name %></td>
      <td>
        <%= link_to "Destroy", ii, data: { turbo_method: :delete, turbo_confirm: "Delete?" } %>
      </td>
    </tr>
  <% end %>
</table>

app/views/inventory_items/new.html.erb
<!-- app/views/inventory_items/new.html.erb -->
<h1>New Inventory Item</h1>
<%= render "form", inventory_item: @inventory_item %>
<p><%= link_to "Back", inventory_items_path %></p>

app/views/inventory_items/show.html.erb
<!-- app/views/inventory_items/show.html.erb -->
<p><%= link_to "Back", inventory_items_path %> | <%= link_to "Edit", edit_inventory_item_path(@inventory_item) %></p>
<h1><%= @inventory_item.name %></h1>
<p><strong>Qty:</strong> <%= @inventory_item.qty_have %> <%= @inventory_item.unit %></p>
<p><strong>Location:</strong> <%= @inventory_item.location&.name %></p>