config/routes.rb
Rails.application.routes.draw do

  root "home#index"

  resources :items do
    member do
      get  :materials      # /items/:id/materials
      post :materials_post      # bulk add/update
    end
  end
  get  "shopping",          to: "shopping#index"
  post "shopping/purchase", to: "shopping#purchase", as: :shopping_purchase

  resources :material_requirements
  resources :inventory_items
  resources :item_blocks
  resources :categories
  resources :moods
  resources :locations
  resources :shops
  resources :items

  get  "/login",  to: "sessions#new"
  post "/login",  to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  get  "/planner", to: "schedule_entries#index", as: :planner
  resources :schedule_entries, only: [:create, :destroy] do
    collection do
      delete :clear # ?on_date=YYYY-MM-DD&day_part=morning
    end
  end

end

app/models/item_block.rb
class ItemBlock < ApplicationRecord
  belongs_to :blocker, class_name: "Item"
  belongs_to :blocked, class_name: "Item"

  validates :blocker_id, :blocked_id, presence: true
  validates :blocked_id, uniqueness: { scope: :blocker_id } # no dup edges
end

app/controllers/item_blocks_controller.rb
# app/controllers/item_blocks_controller.rb
class ItemBlocksController < ApplicationController
  before_action :set_item_block, only: %i[show edit update destroy]

  def index
    @item_blocks = ItemBlock.includes(:blocker, :blocked)
  end

  def show; end

  def new
    @item_block = ItemBlock.new(blocked_id: params[:blocked_id], blocker_id: params[:blocker_id])
  end

  def edit; end

  def create
    @item_block = ItemBlock.new(item_block_params)
    if @item_block.save
      redirect_to item_blocks_path, notice: "Blocker edge created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @item_block.update(item_block_params)
      redirect_to item_blocks_path, notice: "Blocker edge updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @item_block.destroy
    redirect_to item_blocks_url, notice: "Blocker edge deleted."
  end

  private
  def set_item_block
    @item_block = ItemBlock.find(params[:id])
  end

  def item_block_params
    params.require(:item_block).permit(:blocker_id, :blocked_id)
  end
end

app/views/item_blocks/_form.html.erb
<!-- app/views/item_blocks/_form.html.erb -->
<%= form_with(model: item_block) do |f| %>
  <% if item_block.errors.any? %>
    <div style="color:red"><%= item_block.errors.full_messages.to_sentence %></div>
  <% end %>
  <p>Blocker<br>
    <%= f.collection_select :blocker_id, Item.order(:title), :id, :title, include_blank: false %>
  </p>
  <p>Blocked<br>
    <%= f.collection_select :blocked_id, Item.order(:title), :id, :title, include_blank: false %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/item_blocks/edit.html.erb
<!-- app/views/item_blocks/edit.html.erb -->
<h1>Edit Block Edge</h1>
<%= render "form", item_block: @item_block %>
<p><%= link_to "Back", @item_block %></p>

app/views/item_blocks/index.html.erb
<!-- app/views/item_blocks/index.html.erb -->
<h1>Item Blocks</h1>
<p><%= link_to "Back", root_path %></p>
<p><%= link_to "New Block Edge", new_item_block_path %></p>
<table border="1" cellpadding="6">
  <tr><th>Blocker</th><th>→</th><th>Blocked</th><th></th></tr>
  <% @item_blocks.each do |ib| %>
    <tr>
      <td><%= link_to ib.blocker.title, ib.blocker %></td>
      <td>→</td>
      <td><%= link_to ib.blocked.title, ib.blocked %></td>
      <td>
        <%= link_to "Show", ib %> |
        <%= link_to "Edit", edit_item_block_path(ib) %> |
        <%= link_to "Destroy", ib, data: { turbo_method: :delete, turbo_confirm: "Delete?" } %>
      </td>
    </tr>
  <% end %>
</table>

app/views/item_blocks/new.html.erb
<!-- app/views/item_blocks/new.html.erb -->
<h1>New Block Edge</h1>
<%= render "form", item_block: @item_block %>
<p><%= link_to "Back", item_blocks_path %></p>

app/views/item_blocks/show.html.erb
<!-- app/views/item_blocks/show.html.erb -->
<p><%= link_to "Back", item_blocks_path %> | <%= link_to "Edit", edit_item_block_path(@item_block) %></p>
<h1>Block Edge</h1>
<p><strong>Blocker:</strong> <%= link_to @item_block.blocker.title, @item_block.blocker %></p>
<p><strong>Blocked:</strong> <%= link_to @item_block.blocked.title, @item_block.blocked %></p>